// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_socialmedia_added_url : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_socialmedia_added_url));
        
        string IMigrationMetadata.Id
        {
            get { return "202406131022202_mig_socialmedia_added_url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
