// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_educatortable_addmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_educatortable_addmail));
        
        string IMigrationMetadata.Id
        {
            get { return "202406140842392_mig_educatortable_addmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
